services:
  app:
    build: .
    container_name: interfit-app
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DATABASE: interfit
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: interfit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: