services:
  app:
    build: .
    container_name: interfit-app

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      MONGODB_DATABASE: interfit

    volumes:
      - .:/app